### ISSUE TITLE
Upload only worked once

### ISSUE THREAD

**Issue by BNNorman** [leCandas/M5Stamp-C3#2] opened 2022-07-29 15:38 UTC
Thanks for this work. 

I have C3U stamp which I bought to 'play' with. It doesn't appear in the platformio boards then I found this repo and wondered if this would work

I built and uploaded your sketch to my stamp successfully but nothing happened. So, I added a few extra Serial.println() and rebuilt. However, this time platformio would not upload to the stamp (Yes I power cycled with the G9 button pressed). Here's the failing  output:-
```
esptool.py v3.2
Merged 2 ELF sections
Configuring upload protocol...
AVAILABLE: esp-prog, espota, esptool, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa
CURRENT: upload_protocol = esptool
Looking for upload port...
Error: Please specify `upload_port` for environment or use global `--upload-port` option.
For some development platforms it can be a USB flash drive (i.e. /media/<user>/<device name>)
*** [upload] Explicit exit, status 1
================================================ [FAILED] Took 71.03 seconds ================================================
```

When something like this happens I usually trash the build folder and rebuild - but this has hsd no effect.

I would apprecviate it if you have any ideas on how to get platformio to upload to the device again, unless, of course, the first upload turned it into a brick.

Regards & nmany thanks for any light you can throw on this.
Brian

**Comment by nicolasdb** [comment] 2022-08-19 14:44
hello, any update on that situation? 
I am afraid to test it and brick on the first attempt the only board I have. 
in the meantime, I will try with arduino IDE .... 
Thanks

**Comment by BNNorman** [comment] 2022-08-19 14:49
Not yet. I've been busy with other stuff but the stamp is lurking on my desk waiting to be played with again.

**Comment by nicolasdb** [comment] 2022-08-19 15:05
:sweat_smile: 
ok thanks for this fast update. 
I have forked this repo to explore on my side. 
I'm getting started on this board and I will try to collect the tutorials and to document my steps.

**Comment by BNNorman** [comment] 2022-08-21 09:23
Thanks for 'Exploring ...' link. Nice work. I'm back to investigating the  C3U. I'll have a go with the Arduino GUI. Maybe an FTDI would help with Platformio.

**Comment by BNNorman** [comment] 2022-08-27 09:17
Finally got platformio to work. I was having some problems with platformio uploading the firmware (not selecting the bootloader. It was looking for bootloader__80m.bin instead of bootloader_dio_80m.bin so I ended up re-installing platformio.

Anyway, below is my platformio.ini. Windows now gives me the dah-donk sound when the M5STAMP-C3U is powered on with the  middle button pressed.

My sketch simply cycled the RGB LED through a number of colour settings - just to prove it was working.

I read, somewhere, that qio didn't work well but dio did so I changed the flashmode to dio. It worked. So, It appears I don't have a brick after all.


```
[env:ESP32-C3]
platform = espressif32
board =ESP32-C3-DevKitM-1
framework = arduino
lib_deps = fastled/FastLED@^3.5.0
;upload_port = COM8
board_build.flash_mode = dio
```

**Comment by nicolasdb** [comment] 2022-09-09 09:36
:warning:  I received an error. The board was not recognized. `Unknown board ID 'ESP32-C3-DevKitM-1'`

But then I copy paste the name from the [espressif docs.](https://docs.platformio.org/en/stable/boards/espressif32/esp32-c3-devkitm-1.html)
`board = esp32-c3-devkitm-1`
And it compiled ok. Must be case sensitive.

**Comment by nicolasdb** [comment] 2022-09-09 09:57
:warning: and an error during upload 
```
esptool write_flash: error: argument <address> <filename>: [Errno 2] No such file or directory: 
'.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32c3/bin/bootloader__80m.bin'
*** [upload] Error 2
```

Which is resolved by adding `platform_packages = framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.3`
there is [an error during upload caused by the version 2.0.4](https://techoverflow.net/2022/07/28/how-to-fix-platformio-no-such-file-or-directory-bootloader__80m-bin-bootloader__40m-bin/), so this force to use version 2.0.3 which upload no problemo

**Comment by BNNorman** [comment] 2022-09-09 12:40
Thanks for that. I got it to upload but I'll add that to platformio.ini next time I use it.

I don't recollect getting the unknown board error.

**Comment by leCandas** [comment] 2022-09-24 09:19
Quite a lot of time passed since the initial push, 
I have updated the platformio.ini 
Also added FreeRTOS into the example

**Closed as completed by leCandas** 2022-09-24 09:19 UTC
